@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Apr 28 18:56:02 +0200 2022
REM SW Build 3367213 on Tue Oct 19 02:48:09 MDT 2021
REM
REM IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_driver_7seg_8digits_behav -key {Behavioral:sim_1:Functional:tb_driver_7seg_8digits} -tclbatch tb_driver_7seg_8digits.tcl -view D:/vut/letni - 2/DE1/digital-electronics-1/labs/projekt2/project/tb_cnt_up_down_behav.wcfg -view D:/vut/letni - 2/DE1/digital-electronics-1/labs/projekt2/project/tb_driver_7seg_8digits_behav.wcfg -view D:/vut/letni - 2/DE1/digital-electronics-1/labs/projekt2/project/tb_hex_7seg_behav.wcfg -view D:/vut/letni - 2/DE1/digital-electronics-1/labs/projekt2/project/tb_clock_enable_behav.wcfg -log simulate.log"
call xsim  tb_driver_7seg_8digits_behav -key {Behavioral:sim_1:Functional:tb_driver_7seg_8digits} -tclbatch tb_driver_7seg_8digits.tcl -view D:/vut/letni - 2/DE1/digital-electronics-1/labs/projekt2/project/tb_cnt_up_down_behav.wcfg -view D:/vut/letni - 2/DE1/digital-electronics-1/labs/projekt2/project/tb_driver_7seg_8digits_behav.wcfg -view D:/vut/letni - 2/DE1/digital-electronics-1/labs/projekt2/project/tb_hex_7seg_behav.wcfg -view D:/vut/letni - 2/DE1/digital-electronics-1/labs/projekt2/project/tb_clock_enable_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
